name: citysense_flutter
description: "CitySense - Keep Your City Clean & Beautiful"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Authentication - Supabase
  supabase_flutter: ^2.3.0
  webview_flutter: ^4.4.0
  http: ^1.2.0

  # UI & Icons
  lucide_icons: ^0.257.0

  # Storage
  flutter_secure_storage: ^9.0.0

  # Environment
  flutter_dotenv: ^5.1.0

  # URL handling
  url_launcher: ^6.2.5
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  intl: ^0.20.2
  image_picker: ^1.2.1
  geocoding: ^4.0.0
  google_generative_ai: ^0.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  shared_preferences: ^2.5.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env
